//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.PrestamoEjemplarWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="PrestamoEjemplarWS.PrestamoEjemplarWS")]
    public interface PrestamoEjemplarWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse listarPrestamosDevueltos(WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> listarPrestamosDevueltosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse insertarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> insertarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse eliminarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> eliminarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse listarPrestamosSolicitados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> listarPrestamosSolicitadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse listarPrestamosAtrasados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> listarPrestamosAtrasadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse modificarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> modificarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse listarPrestamosNoCulminados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> listarPrestamosNoCulminadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse listarTodosPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> listarTodosPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse obtenerPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> obtenerPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class prestamosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaDevolucionField;
        
        private bool fechaDevolucionFieldSpecified;
        
        private System.DateTime fechaPrestamoField;
        
        private bool fechaPrestamoFieldSpecified;
        
        private System.DateTime fechaSolicitudField;
        
        private bool fechaSolicitudFieldSpecified;
        
        private int idPrestamoField;
        
        private bool idPrestamoFieldSpecified;
        
        private personasDTO personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaDevolucion {
            get {
                return this.fechaDevolucionField;
            }
            set {
                this.fechaDevolucionField = value;
                this.RaisePropertyChanged("fechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDevolucionSpecified {
            get {
                return this.fechaDevolucionFieldSpecified;
            }
            set {
                this.fechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
                this.RaisePropertyChanged("fechaPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPrestamoSpecified {
            get {
                return this.fechaPrestamoFieldSpecified;
            }
            set {
                this.fechaPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                this.fechaSolicitudField = value;
                this.RaisePropertyChanged("fechaSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSolicitudSpecified {
            get {
                return this.fechaSolicitudFieldSpecified;
            }
            set {
                this.fechaSolicitudFieldSpecified = value;
                this.RaisePropertyChanged("fechaSolicitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                this.idPrestamoField = value;
                this.RaisePropertyChanged("idPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPrestamoSpecified {
            get {
                return this.idPrestamoFieldSpecified;
            }
            set {
                this.idPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("idPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public personasDTO persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private double deudaField;
        
        private bool deudaFieldSpecified;
        
        private string direccionField;
        
        private System.DateTime fechaContratoFinalField;
        
        private bool fechaContratoFinalFieldSpecified;
        
        private System.DateTime fechaContratoInicioField;
        
        private bool fechaContratoInicioFieldSpecified;
        
        private System.DateTime fechaSancionFinalField;
        
        private bool fechaSancionFinalFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string maternoField;
        
        private nivelesInglesDTO nivelField;
        
        private string nombreField;
        
        private string paternoField;
        
        private sedesDTO sedeField;
        
        private string telefonoField;
        
        private tipoPersona tipoField;
        
        private bool tipoFieldSpecified;
        
        private turnos turnoField;
        
        private bool turnoFieldSpecified;
        
        private bool vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double deuda {
            get {
                return this.deudaField;
            }
            set {
                this.deudaField = value;
                this.RaisePropertyChanged("deuda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deudaSpecified {
            get {
                return this.deudaFieldSpecified;
            }
            set {
                this.deudaFieldSpecified = value;
                this.RaisePropertyChanged("deudaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaContratoFinal {
            get {
                return this.fechaContratoFinalField;
            }
            set {
                this.fechaContratoFinalField = value;
                this.RaisePropertyChanged("fechaContratoFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoFinalSpecified {
            get {
                return this.fechaContratoFinalFieldSpecified;
            }
            set {
                this.fechaContratoFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaContratoInicio {
            get {
                return this.fechaContratoInicioField;
            }
            set {
                this.fechaContratoInicioField = value;
                this.RaisePropertyChanged("fechaContratoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoInicioSpecified {
            get {
                return this.fechaContratoInicioFieldSpecified;
            }
            set {
                this.fechaContratoInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaSancionFinal {
            get {
                return this.fechaSancionFinalField;
            }
            set {
                this.fechaSancionFinalField = value;
                this.RaisePropertyChanged("fechaSancionFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSancionFinalSpecified {
            get {
                return this.fechaSancionFinalFieldSpecified;
            }
            set {
                this.fechaSancionFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaSancionFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public nivelesInglesDTO nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public sedesDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public tipoPersona tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public turnos turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class nivelesInglesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idNivelField;
        
        private nivel nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idNivel {
            get {
                return this.idNivelField;
            }
            set {
                this.idNivelField = value;
                this.RaisePropertyChanged("idNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public nivel nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivel {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class prestamosDeEjemplaresDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoPrestamoEjemplar estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRealDevolucionField;
        
        private bool fechaRealDevolucionFieldSpecified;
        
        private int idEjemplarField;
        
        private bool idEjemplarFieldSpecified;
        
        private int idPrestamoField;
        
        private bool idPrestamoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoPrestamoEjemplar estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaRealDevolucion {
            get {
                return this.fechaRealDevolucionField;
            }
            set {
                this.fechaRealDevolucionField = value;
                this.RaisePropertyChanged("fechaRealDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRealDevolucionSpecified {
            get {
                return this.fechaRealDevolucionFieldSpecified;
            }
            set {
                this.fechaRealDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRealDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEjemplar {
            get {
                return this.idEjemplarField;
            }
            set {
                this.idEjemplarField = value;
                this.RaisePropertyChanged("idEjemplar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEjemplarSpecified {
            get {
                return this.idEjemplarFieldSpecified;
            }
            set {
                this.idEjemplarFieldSpecified = value;
                this.RaisePropertyChanged("idEjemplarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                this.idPrestamoField = value;
                this.RaisePropertyChanged("idPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPrestamoSpecified {
            get {
                return this.idPrestamoFieldSpecified;
            }
            set {
                this.idPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("idPrestamoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum estadoPrestamoEjemplar {
        
        /// <remarks/>
        SOLICITADO,
        
        /// <remarks/>
        PRESTADO,
        
        /// <remarks/>
        DEVUELTO,
        
        /// <remarks/>
        ATRASADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoPersona {
        
        /// <remarks/>
        PROFESOR,
        
        /// <remarks/>
        ADMINISTRADOR,
        
        /// <remarks/>
        ESTUDIANTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum turnos {
        
        /// <remarks/>
        MANHANA,
        
        /// <remarks/>
        TARDE,
        
        /// <remarks/>
        NOCHE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosDevueltos", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosDevueltosRequest {
        
        public listarPrestamosDevueltosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosDevueltosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosDevueltosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return;
        
        public listarPrestamosDevueltosResponse() {
        }
        
        public listarPrestamosDevueltosResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto;
        
        public insertarPrestamoEjemplarRequest() {
        }
        
        public insertarPrestamoEjemplarRequest(int idPestamo, int idEjemplar, WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            this.idPestamo = idPestamo;
            this.idEjemplar = idEjemplar;
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPrestamoEjemplarResponse() {
        }
        
        public insertarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public eliminarPrestamoEjemplarRequest() {
        }
        
        public eliminarPrestamoEjemplarRequest(int idPrestamo, int idEjemplar) {
            this.idPrestamo = idPrestamo;
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPrestamoEjemplarResponse() {
        }
        
        public eliminarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosSolicitados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosSolicitadosRequest {
        
        public listarPrestamosSolicitadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosSolicitadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosSolicitadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return;
        
        public listarPrestamosSolicitadosResponse() {
        }
        
        public listarPrestamosSolicitadosResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosAtrasados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosAtrasadosRequest {
        
        public listarPrestamosAtrasadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosAtrasadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosAtrasadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return;
        
        public listarPrestamosAtrasadosResponse() {
        }
        
        public listarPrestamosAtrasadosResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto;
        
        public modificarPrestamoEjemplarRequest() {
        }
        
        public modificarPrestamoEjemplarRequest(WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPrestamoEjemplarResponse() {
        }
        
        public modificarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosNoCulminados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosNoCulminadosRequest {
        
        public listarPrestamosNoCulminadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosNoCulminadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosNoCulminadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return;
        
        public listarPrestamosNoCulminadosResponse() {
        }
        
        public listarPrestamosNoCulminadosResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTodosPrestamoEjemplarRequest {
        
        public listarTodosPrestamoEjemplarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTodosPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarTodosPrestamoEjemplarResponse() {
        }
        
        public listarTodosPrestamoEjemplarResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public obtenerPrestamoEjemplarRequest() {
        }
        
        public obtenerPrestamoEjemplarRequest(int idPrestamo, int idEjemplar) {
            this.idPrestamo = idPrestamo;
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO @return;
        
        public obtenerPrestamoEjemplarResponse() {
        }
        
        public obtenerPrestamoEjemplarResponse(WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrestamoEjemplarWSChannel : WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamoEjemplarWSClient : System.ServiceModel.ClientBase<WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS>, WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS {
        
        public PrestamoEjemplarWSClient() {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoEjemplarWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosDevueltos(WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request) {
            return base.Channel.listarPrestamosDevueltos(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] listarPrestamosDevueltos() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest();
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosDevueltos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosDevueltosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request) {
            return base.Channel.listarPrestamosDevueltosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> listarPrestamosDevueltosAsync() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosDevueltosRequest();
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosDevueltosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.insertarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request) {
            return base.Channel.insertarPrestamoEjemplar(request);
        }
        
        public int insertarPrestamoEjemplar(int idPestamo, int idEjemplar, WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest();
            inValue.idPestamo = idPestamo;
            inValue.idEjemplar = idEjemplar;
            inValue.dto = dto;
            WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).insertarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.insertarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request) {
            return base.Channel.insertarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> insertarPrestamoEjemplarAsync(int idPestamo, int idEjemplar, WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest();
            inValue.idPestamo = idPestamo;
            inValue.idEjemplar = idEjemplar;
            inValue.dto = dto;
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).insertarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.eliminarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request) {
            return base.Channel.eliminarPrestamoEjemplar(request);
        }
        
        public int eliminarPrestamoEjemplar(int idPrestamo, int idEjemplar) {
            WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).eliminarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.eliminarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request) {
            return base.Channel.eliminarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> eliminarPrestamoEjemplarAsync(int idPrestamo, int idEjemplar) {
            WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).eliminarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosSolicitados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request) {
            return base.Channel.listarPrestamosSolicitados(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] listarPrestamosSolicitados() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest();
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosSolicitados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosSolicitadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request) {
            return base.Channel.listarPrestamosSolicitadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> listarPrestamosSolicitadosAsync() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest();
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosSolicitadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosAtrasados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request) {
            return base.Channel.listarPrestamosAtrasados(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] listarPrestamosAtrasados() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest();
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosAtrasados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosAtrasadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request) {
            return base.Channel.listarPrestamosAtrasadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> listarPrestamosAtrasadosAsync() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest();
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosAtrasadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.modificarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request) {
            return base.Channel.modificarPrestamoEjemplar(request);
        }
        
        public int modificarPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest();
            inValue.dto = dto;
            WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).modificarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.modificarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request) {
            return base.Channel.modificarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> modificarPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest();
            inValue.dto = dto;
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).modificarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosNoCulminados(WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request) {
            return base.Channel.listarPrestamosNoCulminados(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDTO[] listarPrestamosNoCulminados() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest();
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosNoCulminados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosNoCulminadosAsync(WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request) {
            return base.Channel.listarPrestamosNoCulminadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> listarPrestamosNoCulminadosAsync() {
            WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest();
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosNoCulminadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarTodosPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request) {
            return base.Channel.listarTodosPrestamoEjemplar(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarTodosPrestamoEjemplar() {
            WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest();
            WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarTodosPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.listarTodosPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request) {
            return base.Channel.listarTodosPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> listarTodosPrestamoEjemplarAsync() {
            WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest();
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarTodosPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.obtenerPrestamoEjemplar(WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request) {
            return base.Channel.obtenerPrestamoEjemplar(request);
        }
        
        public WA_Prueba.PrestamoEjemplarWS.prestamosDeEjemplaresDTO obtenerPrestamoEjemplar(int idPrestamo, int idEjemplar) {
            WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse retVal = ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).obtenerPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS.obtenerPrestamoEjemplarAsync(WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request) {
            return base.Channel.obtenerPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> obtenerPrestamoEjemplarAsync(int idPrestamo, int idEjemplar) {
            WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest inValue = new WA_Prueba.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            return ((WA_Prueba.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).obtenerPrestamoEjemplarAsync(inValue);
        }
    }
}
