//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.TemaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="TemaWS.TemaWS")]
    public interface TemaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/modificarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/modificarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.TemaWS.modificarTemaResponse modificarTema(WA_Prueba.TemaWS.modificarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/modificarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/modificarTemaResponse")]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.modificarTemaResponse> modificarTemaAsync(WA_Prueba.TemaWS.modificarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/eliminarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/eliminarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.TemaWS.eliminarTemaResponse eliminarTema(WA_Prueba.TemaWS.eliminarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/eliminarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/eliminarTemaResponse")]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.eliminarTemaResponse> eliminarTemaAsync(WA_Prueba.TemaWS.eliminarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/obtenerTemaPorIdRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/obtenerTemaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.TemaWS.obtenerTemaPorIdResponse obtenerTemaPorId(WA_Prueba.TemaWS.obtenerTemaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/obtenerTemaPorIdRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/obtenerTemaPorIdResponse")]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.obtenerTemaPorIdResponse> obtenerTemaPorIdAsync(WA_Prueba.TemaWS.obtenerTemaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/listarTemasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/listarTemasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.TemaWS.listarTemasResponse listarTemas(WA_Prueba.TemaWS.listarTemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/listarTemasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/listarTemasResponse")]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.listarTemasResponse> listarTemasAsync(WA_Prueba.TemaWS.listarTemasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/insertarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/insertarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.TemaWS.insertarTemaResponse insertarTema(WA_Prueba.TemaWS.insertarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/TemaWS/insertarTemaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/TemaWS/insertarTemaResponse")]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.insertarTemaResponse> insertarTemaAsync(WA_Prueba.TemaWS.insertarTemaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class temasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoria categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string descripcionField;
        
        private int idTemaField;
        
        private bool idTemaFieldSpecified;
        
        private temasDTO temaPadreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTema {
            get {
                return this.idTemaField;
            }
            set {
                this.idTemaField = value;
                this.RaisePropertyChanged("idTema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTemaSpecified {
            get {
                return this.idTemaFieldSpecified;
            }
            set {
                this.idTemaFieldSpecified = value;
                this.RaisePropertyChanged("idTemaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public temasDTO temaPadre {
            get {
                return this.temaPadreField;
            }
            set {
                this.temaPadreField = value;
                this.RaisePropertyChanged("temaPadre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum categoria {
        
        /// <remarks/>
        GENERO,
        
        /// <remarks/>
        EDAD,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTema", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.TemaWS.temasDTO tema;
        
        public modificarTemaRequest() {
        }
        
        public modificarTemaRequest(WA_Prueba.TemaWS.temasDTO tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTemaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTemaResponse() {
        }
        
        public modificarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTema", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTema;
        
        public eliminarTemaRequest() {
        }
        
        public eliminarTemaRequest(int idTema) {
            this.idTema = idTema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTemaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTemaResponse() {
        }
        
        public eliminarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTemaPorId", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerTemaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTema;
        
        public obtenerTemaPorIdRequest() {
        }
        
        public obtenerTemaPorIdRequest(int idTema) {
            this.idTema = idTema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTemaPorIdResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerTemaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.TemaWS.temasDTO @return;
        
        public obtenerTemaPorIdResponse() {
        }
        
        public obtenerTemaPorIdResponse(WA_Prueba.TemaWS.temasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTemasRequest {
        
        public listarTemasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.TemaWS.temasDTO[] @return;
        
        public listarTemasResponse() {
        }
        
        public listarTemasResponse(WA_Prueba.TemaWS.temasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTema", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.TemaWS.temasDTO tema;
        
        public insertarTemaRequest() {
        }
        
        public insertarTemaRequest(WA_Prueba.TemaWS.temasDTO tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTemaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTemaResponse() {
        }
        
        public insertarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TemaWSChannel : WA_Prueba.TemaWS.TemaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemaWSClient : System.ServiceModel.ClientBase<WA_Prueba.TemaWS.TemaWS>, WA_Prueba.TemaWS.TemaWS {
        
        public TemaWSClient() {
        }
        
        public TemaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.TemaWS.modificarTemaResponse WA_Prueba.TemaWS.TemaWS.modificarTema(WA_Prueba.TemaWS.modificarTemaRequest request) {
            return base.Channel.modificarTema(request);
        }
        
        public int modificarTema(WA_Prueba.TemaWS.temasDTO tema) {
            WA_Prueba.TemaWS.modificarTemaRequest inValue = new WA_Prueba.TemaWS.modificarTemaRequest();
            inValue.tema = tema;
            WA_Prueba.TemaWS.modificarTemaResponse retVal = ((WA_Prueba.TemaWS.TemaWS)(this)).modificarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.modificarTemaResponse> WA_Prueba.TemaWS.TemaWS.modificarTemaAsync(WA_Prueba.TemaWS.modificarTemaRequest request) {
            return base.Channel.modificarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.TemaWS.modificarTemaResponse> modificarTemaAsync(WA_Prueba.TemaWS.temasDTO tema) {
            WA_Prueba.TemaWS.modificarTemaRequest inValue = new WA_Prueba.TemaWS.modificarTemaRequest();
            inValue.tema = tema;
            return ((WA_Prueba.TemaWS.TemaWS)(this)).modificarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.TemaWS.eliminarTemaResponse WA_Prueba.TemaWS.TemaWS.eliminarTema(WA_Prueba.TemaWS.eliminarTemaRequest request) {
            return base.Channel.eliminarTema(request);
        }
        
        public int eliminarTema(int idTema) {
            WA_Prueba.TemaWS.eliminarTemaRequest inValue = new WA_Prueba.TemaWS.eliminarTemaRequest();
            inValue.idTema = idTema;
            WA_Prueba.TemaWS.eliminarTemaResponse retVal = ((WA_Prueba.TemaWS.TemaWS)(this)).eliminarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.eliminarTemaResponse> WA_Prueba.TemaWS.TemaWS.eliminarTemaAsync(WA_Prueba.TemaWS.eliminarTemaRequest request) {
            return base.Channel.eliminarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.TemaWS.eliminarTemaResponse> eliminarTemaAsync(int idTema) {
            WA_Prueba.TemaWS.eliminarTemaRequest inValue = new WA_Prueba.TemaWS.eliminarTemaRequest();
            inValue.idTema = idTema;
            return ((WA_Prueba.TemaWS.TemaWS)(this)).eliminarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.TemaWS.obtenerTemaPorIdResponse WA_Prueba.TemaWS.TemaWS.obtenerTemaPorId(WA_Prueba.TemaWS.obtenerTemaPorIdRequest request) {
            return base.Channel.obtenerTemaPorId(request);
        }
        
        public WA_Prueba.TemaWS.temasDTO obtenerTemaPorId(int idTema) {
            WA_Prueba.TemaWS.obtenerTemaPorIdRequest inValue = new WA_Prueba.TemaWS.obtenerTemaPorIdRequest();
            inValue.idTema = idTema;
            WA_Prueba.TemaWS.obtenerTemaPorIdResponse retVal = ((WA_Prueba.TemaWS.TemaWS)(this)).obtenerTemaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.obtenerTemaPorIdResponse> WA_Prueba.TemaWS.TemaWS.obtenerTemaPorIdAsync(WA_Prueba.TemaWS.obtenerTemaPorIdRequest request) {
            return base.Channel.obtenerTemaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.TemaWS.obtenerTemaPorIdResponse> obtenerTemaPorIdAsync(int idTema) {
            WA_Prueba.TemaWS.obtenerTemaPorIdRequest inValue = new WA_Prueba.TemaWS.obtenerTemaPorIdRequest();
            inValue.idTema = idTema;
            return ((WA_Prueba.TemaWS.TemaWS)(this)).obtenerTemaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.TemaWS.listarTemasResponse WA_Prueba.TemaWS.TemaWS.listarTemas(WA_Prueba.TemaWS.listarTemasRequest request) {
            return base.Channel.listarTemas(request);
        }
        
        public WA_Prueba.TemaWS.temasDTO[] listarTemas() {
            WA_Prueba.TemaWS.listarTemasRequest inValue = new WA_Prueba.TemaWS.listarTemasRequest();
            WA_Prueba.TemaWS.listarTemasResponse retVal = ((WA_Prueba.TemaWS.TemaWS)(this)).listarTemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.listarTemasResponse> WA_Prueba.TemaWS.TemaWS.listarTemasAsync(WA_Prueba.TemaWS.listarTemasRequest request) {
            return base.Channel.listarTemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.TemaWS.listarTemasResponse> listarTemasAsync() {
            WA_Prueba.TemaWS.listarTemasRequest inValue = new WA_Prueba.TemaWS.listarTemasRequest();
            return ((WA_Prueba.TemaWS.TemaWS)(this)).listarTemasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.TemaWS.insertarTemaResponse WA_Prueba.TemaWS.TemaWS.insertarTema(WA_Prueba.TemaWS.insertarTemaRequest request) {
            return base.Channel.insertarTema(request);
        }
        
        public int insertarTema(WA_Prueba.TemaWS.temasDTO tema) {
            WA_Prueba.TemaWS.insertarTemaRequest inValue = new WA_Prueba.TemaWS.insertarTemaRequest();
            inValue.tema = tema;
            WA_Prueba.TemaWS.insertarTemaResponse retVal = ((WA_Prueba.TemaWS.TemaWS)(this)).insertarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.TemaWS.insertarTemaResponse> WA_Prueba.TemaWS.TemaWS.insertarTemaAsync(WA_Prueba.TemaWS.insertarTemaRequest request) {
            return base.Channel.insertarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.TemaWS.insertarTemaResponse> insertarTemaAsync(WA_Prueba.TemaWS.temasDTO tema) {
            WA_Prueba.TemaWS.insertarTemaRequest inValue = new WA_Prueba.TemaWS.insertarTemaRequest();
            inValue.tema = tema;
            return ((WA_Prueba.TemaWS.TemaWS)(this)).insertarTemaAsync(inValue);
        }
    }
}
